CREATE TABLE usuario(
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role ENUM('ADMIN', 'USER') NOT NULL
);